/**
 * templates.js – Strip template definitions for STRIPPIN
 * Each template defines: id, name, mode (bw/ceria), style, slots, header, footer
 */

const TEMPLATES = {
  bw: [
    {
      id: 'bw-classic',
      name: 'Classic Strip',
      mode: 'bw',
      bg: '#ffffff',
      border: '2px solid #000',
      slots: [
        { shape: 'rect', label: 'Masukkan Foto 1' },
        { shape: 'rect', label: 'Masukkan Foto 2' },
        { shape: 'rect', label: 'Masukkan Foto 3' },
      ],
      footer: { text: 'HAPPY Strippin ✦', bg: '#000', color: '#fff' },
      filter: 'grayscale(100%)',
    },
    {
      id: 'bw-cat',
      name: 'Strippin Love',
      mode: 'bw',
      bg: '#f5f5f5',
      border: '2px solid #333',
      slots: [
        { shape: 'oval', label: 'Foto 1' },
        { shape: 'oval', label: 'Foto 2' },
        { shape: 'oval', label: 'Foto 3' },
      ],
      footer: { text: 'STRIPPIN love cubing', bg: '#f5f5f5', color: '#333' },
      filter: 'grayscale(100%)',
    },
    {
      id: 'bw-dots',
      name: 'Happy Dots',
      mode: 'bw',
      bg: '#fff',
      border: '3px solid #000',
      borderDots: true,
      slots: [
        { shape: 'rect', label: 'Foto 1' },
        { shape: 'circle', label: 'Foto 2' },
        { shape: 'rect', label: 'Foto 3' },
      ],
      footer: { text: 'HAPPY Strippin ✦ HAPPY', bg: '#000', color: '#fff' },
      filter: 'grayscale(100%)',
    },
    {
      id: 'bw-film',
      name: 'Film Strip',
      mode: 'bw',
      bg: '#1a1a1a',
      border: '3px solid #000',
      filmHoles: true,
      slots: [
        { shape: 'rect', label: 'Foto 1' },
        { shape: 'rect', label: 'Foto 2' },
        { shape: 'rect', label: 'Foto 3' },
      ],
      footer: { text: 'STRIPPIN', bg: '#000', color: '#fff' },
      filter: 'grayscale(100%)',
    },
    {
      id: 'bw-together',
      name: 'Together Forever',
      mode: 'bw',
      bg: '#1a0000',
      border: '2px solid #5a0000',
      slots: [
        { shape: 'oval', label: 'Foto 1' },
        { shape: 'oval', label: 'Foto 2' },
      ],
      header: { text: 'TOGETHER\nForever', bg: 'transparent', color: '#fff' },
      footer: { text: 'STRIPPIN', bg: 'transparent', color: '#fff' },
      filter: 'grayscale(80%) contrast(1.2)',
    },
    {
      id: 'bw-book',
      name: 'Book Story',
      mode: 'bw',
      bg: '#fafafa',
      border: '1.5px solid #aaa',
      slots: [
        { shape: 'rect', label: 'Foto 1' },
        { shape: 'rect', label: 'Foto 2' },
        { shape: 'rect', label: 'Foto 3' },
      ],
      header: { text: 'BOOK STORIES', bg: '#fff', color: '#555' },
      footer: { text: 'BOOK STORIES', bg: '#fff', color: '#555' },
      filter: 'grayscale(90%) sepia(20%)',
    },
  ],

  ceria: [
    {
      id: 'ceria-pink',
      name: 'Pink Leopard',
      mode: 'ceria',
      bg: '#f9c6d0',
      border: '3px dashed #e8a0b4',
      slots: [
        { shape: 'rect', label: 'Foto 1' },
        { shape: 'rect', label: 'Foto 2' },
        { shape: 'rect', label: 'Foto 3' },
      ],
      footer: { text: 'studio Strippin ♥', bg: '#f9c6d0', color: '#a30030' },
    },
    {
      id: 'ceria-moment',
      name: 'Moment Captured',
      mode: 'ceria',
      bg: '#fde68a',
      border: '2px solid #f59e0b',
      slots: [
        { shape: 'rect', label: 'Foto 1' },
        { shape: 'rect', label: 'Foto 2' },
      ],
      header: { text: 'MOMENT\nCaptured', bg: '#fde68a', color: '#92400e', italic: true },
      footer: { text: 'STRIPPIN', bg: '#fde68a', color: '#92400e' },
    },
    {
      id: 'ceria-special',
      name: 'Special Moments',
      mode: 'ceria',
      bg: '#fff0f0',
      border: '2px solid #f87171',
      slots: [
        { shape: 'rect', label: 'Foto 1' },
        { shape: 'rect', label: 'Foto 2' },
        { shape: 'rect', label: 'Foto 3' },
      ],
      footer: { text: 'SPECIAL Moments', bg: '#f87171', color: '#fff' },
    },
    {
      id: 'ceria-opening',
      name: 'Opening',
      mode: 'ceria',
      bg: '#fce7f3',
      border: '3px solid #ec4899',
      slots: [
        { shape: 'rect', label: 'Foto 1' },
        { shape: 'rect', label: 'Foto 2' },
        { shape: 'rect', label: 'Foto 3' },
        { shape: 'rect', label: 'Foto 4' },
      ],
      footer: { text: 'Opening · STRAPPÍN', bg: '#ec4899', color: '#fff' },
    },
    {
      id: 'ceria-stripchallenge',
      name: '10 Strippin Challenge',
      mode: 'ceria',
      bg: '#dbeafe',
      border: '2px solid #93c5fd',
      slots: [
        { shape: 'circle', label: 'Foto 1' },
        { shape: 'circle', label: 'Foto 2' },
        { shape: 'circle', label: 'Foto 3' },
      ],
      header: { text: '10\nStrippin Challenge', bg: '#dbeafe', color: '#1e40af' },
    },
    {
      id: 'ceria-gingham',
      name: 'Gingham Strippin',
      mode: 'ceria',
      bg: '#fef2f2',
      border: '2px solid #fca5a5',
      gingham: true,
      slots: [
        { shape: 'rect', label: 'Foto 1' },
        { shape: 'rect', label: 'Foto 2' },
      ],
      footer: { text: 'Strippin', bg: '#fef2f2', color: '#b91c1c', italic: true },
    },
    {
      id: 'ceria-scallop',
      name: 'Scallop Frame',
      mode: 'ceria',
      bg: '#fef9c3',
      border: '3px solid #fde047',
      slots: [
        { shape: 'scallop', label: 'Foto 1' },
        { shape: 'scallop', label: 'Foto 2' },
        { shape: 'scallop', label: 'Foto 3' },
      ],
      footer: { text: 'STRIPPIN ✿', bg: '#fde047', color: '#713f12' },
    },
    {
      id: 'ceria-polkared',
      name: 'Red Dots',
      mode: 'ceria',
      bg: '#fff',
      border: '2px solid #7a1c1c',
      polkaDots: true,
      polkaColor: '#7a1c1c',
      slots: [
        { shape: 'circle', label: 'Foto 1' },
        { shape: 'rect', label: 'Foto 2' },
        { shape: 'rect', label: 'Foto 3' },
      ],
      footer: { text: 'Borcelin', bg: '#7a1c1c', color: '#fff' },
    },
  ]
};
